server:
  port: 8081
spring:
  application:
    name: ranking-the-mormels-questions
  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
  jpa:
    hibrernate:
      ddl-auto: update
    show-sql: false
    generate-ddl: true
