server:
  port: 8081
spring:
  application:
    name: ranking-the-mormels-questions
  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
  jpa:
    hibrernate:
      ddl-auto: update
    show-sql: false
    generate-ddl: true
secret:
  key: "SECRET_LOCAL_KEY"
JDBC_DATABASE_URL: jdbc:mysql://localhost:3306/ranking-the-mormels
JDBC_DATABASE_USERNAME: root
JDBC_DATABASE_PASSWORD: admin